spring:
  application:
    name: hello-service
springdoc:
  api-docs:
    path: /hello-service/swagger-ui.html

server:
  port: 8081
  servlet:
    context-path: /hello-service
#eureka:
  #client:
    #serviceUrl:
     # defaultZone: http://localhost:8761/eureka/
  #instance:
    #prefer-ip-address: true
    
 